spring:
  application:
    name: eureka-server
  security:
    user:
      name: usermicroservice
      password: 123456

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    renewal-percent-threshold: 0.85
